FROM alpine:3.23@sha256:51183f2cfa6320055da30872f211093f9ff1d3cf06f39a0bdb212314c5dc7375 as otelc_curl
RUN apk --update add curl

FROM otel/opentelemetry-collector:latest@sha256:dbf77b00f14fceb02453433c7bf9b3438d5723e8b9bd53d61bfe1522d8f7ba5b

COPY --from=otelc_curl / /

COPY ./otel-collector-config.yaml /etc/otel-collector-config.yaml
USER 0
RUN chmod o+r /etc/otel-collector-config.yaml
USER nobody
