name: 'Dependency Review'
on: [pull_request]

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    if: github.repository == 'envoyproxy/envoy'
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@284319451007d5ba938e4afb047f602d7f2cd6c6
