name: 'Dependency Review'
on: [pull_request]

concurrency:
  group: ${{ github.head_ref-github.workflow || github.run_id }}
  cancel-in-progress: true

jobs:
  dependency-review:
    runs-on: ubuntu-22.04
    if: github.repository == 'envoyproxy/envoy'
    steps:
    - name: 'Checkout Repository'
      uses: actions/checkout@v3
    - name: 'Dependency Review'
      uses: actions/dependency-review-action@c74b580d73376b7750d3d2a50bfb8adc2c937507
